config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    resources :relationships, only: [:index, :create, :destroy]
  end
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :body, presence: true, length: { maximum: 255 }
  default_scope -> { order(created_at: :desc) }
  has_one_attached :picture
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  extend Enumerize
  has_many :posts, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy, inverse_of: :follower
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy, inverse_of: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
  enumerize :gender, in: {
    none: 0,
    male: 1,
    female: 2
  }

  def remember
    self.remember_token = User.new_token
    update(remember_digest: User.digest(remember_token))
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def self.digest(string)
    cost = if ActiveModel::SecurePassword.min_cost
             BCrypt::Engine::MIN_COST
           else
             BCrypt::Engine.cost
           end
    BCrypt::Password.create(string, cost: cost)
  end

  def forget
    update(remember_digest: nil)
  end

  def follow(other_user)
    return if self == other_user

    relationships.find_or_create_by(followed_id: other_user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def not_logged_in_user
    return if logged_in?

    flash[:danger] = t 'auth.please_login'
    redirect_to login_url
  end

  def logged_in_user
    redirect_to root_path if logged_in?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :not_logged_in_user
  def new
    @post = Post.new
  end

  def index
    @posts = Post.eager_load(:user).page(params[:page]).per(10)
  end

  def show
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    post = Post.find_by(id: params[:id])
    if post.nil? || post.user_id != current_user.id
      redirect_to root_path
    end
    post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:body, :picture)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
  end

  def create
    user = User.find(params[:id])
    current_user.follow(user)
    redirect_to root_path
  end

  def destroy
    user = User.find(params[:id])
    current_user.unfollow(user)
    redirect_to root_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_user, only: [:new]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスまたはパスワードが違います'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :not_logged_in_user, only: [:show, :edit]
  before_action :logged_in_user, only: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = t 'flash.profile_updated'
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
  end

  def update
    @user = User.find(params[:id])
    redirect_to root_path unless current_user?(@user)
    if @user.update(user_params)
      flash[:success] = t 'users.profile.success'
      redirect_to @user
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :gender, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def current_user?(user)
    user == current_user
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <ul>
        <% if logged_in? %>
          <li><%= link_to "ホーム", root_path %></li>
          <li><%= link_to "投稿する", new_post_path %></li>
          <li><%= link_to "こんにちは#{current_user.name}さん", current_user %></li>
          <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", signup_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<%= paginate @posts %>
<% @posts.each do |post| %>
  <div>ユーザー：<%= post.user.name %></div>
  <% unless post.user == current_user %>
    <% if !current_user.following?(post.user) %>
      <%= button_to 'フォロー', user_relationships_path(user_id: post.user_id, id: post.user_id), method: :post %>
    <% else %>
      <%= button_to 'フォローを外す', user_relationship_path(user_id: post.user_id, id: post.user_id), method: :delete %>
    <% end %>
    <%= post.user.following?(current_user) ? "フォローされています" : "" %>
  <% end %>
  <div>内容：<%= post.body %></div>
  <% if post.picture.attached? %><%= image_tag post.picture %><% end %>
  <div>日時：<%= post.created_at %></div>
  <% if post.user_id == current_user.id %>
    <%= link_to "削除", post_path(post), method: :delete, data: {confirm: "削除しますか？"}  %>
  <% end %>
  <hr>
<% end %>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>投稿</h1>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>  
<% end %>

<%= form_with model: @post do |f| %>
  <p>
    <div><%= f.label :body %></div>
    <div><%= f.text_area :body %></div>
    <div><%= f.file_field :picture %></div>
  </p>
  <%= f.submit "投稿" %>
<% end %>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/relationships/index.html.erb
<h1>フォロー中</h1>
<% @user.followings.each do |following| %>
  <div><%= following.name %></div>
<% end %>
<h1>フォロワー</h1>
<% @user.followers.each do |followers| %>
  <div><%= followers.name %></div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー編集</h1>

<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>  
<% end %>

<%= form_with model: current_user, url: user_path do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :gender %>
    <%= f.select :gender, User.gender.options %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit "更新" %>
<% end %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

<% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>  
<% end %>

<%= form_with model: @user, url: signup_path do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit "登録" %>
<% end %>

<p>すでにアカウントをお持ちですか？ <%= link_to "ログイン", login_path %></p>

app/views/users/show.html.erb
<%= @user.name %>
<div>
フォロワー：<%= link_to "#{@user.followers.count}", user_relationships_path(@user) %>
フォロー：<%= link_to "#{@user.followings.count}", user_relationships_path(@user) %>
</div>
<div>
<%= link_to "ユーザー情報を編集する", edit_user_path(current_user) %>
</div>